package mnplibraryreserve.system;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.application.Platform.exit;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordFIELD = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("Welcome To LRS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(26, 15, 160, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("User Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(26, 75, 80, 19);
        jPanel1.add(Username);
        Username.setBounds(110, 70, 201, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(26, 140, 72, 19);

        passwordFIELD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFIELDKeyPressed(evt);
            }
        });
        jPanel1.add(passwordFIELD);
        passwordFIELD.setBounds(110, 130, 201, 30);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(159, 209, 80, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        freetrial();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordFIELDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFIELDKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER){
      
        Calendar exdate = Calendar.getInstance();
        exdate.set(2030, 7, 2);
        if (Calendar.getInstance().after(exdate)) {
            JOptionPane.showMessageDialog(null, "License Epired");
            ;
        } else {
            PreparedStatement ps;
            ResultSet rs;

            String user_name = Username.getText();
            String password = String.valueOf(passwordFIELD.getPassword());

            String sql = "SELECT * FROM users WHERE username='" + user_name + "' AND password='" + password + "'";
            try {
                ps = DBconnection.Connect().prepareStatement(sql);
                rs = ps.executeQuery();

                if (rs.next()) {
                   
                    JOptionPane.showMessageDialog(null, "Successful login");
                    Home h = new Home();
                    h.setVisible(true);
                    //h.pack();
                    //  h.setLocationRelativeTo(null);
                    //h.setExtendedState(Frame.MAXIMIZED_BOTH);
                    // h.jLabel2.setText("Welcome " +user_name + "");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Credentials Try Again");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
      
      }
    }//GEN-LAST:event_passwordFIELDKeyPressed

    public void freetrial() {

        Calendar exdate = Calendar.getInstance();
        exdate.set(2030, 7, 2);
        if (Calendar.getInstance().after(exdate)) {
            JOptionPane.showMessageDialog(null, "License Epired");
            ;
        } else {
            PreparedStatement ps;
            ResultSet rs;

            String user_name = Username.getText();
            String password = String.valueOf(passwordFIELD.getPassword());

            String sql = "SELECT * FROM users WHERE username='" + user_name + "' AND password='" + password + "'";
            try {
                ps = DBconnection.Connect().prepareStatement(sql);
                rs = ps.executeQuery();

                if (rs.next()) {
                   
                    JOptionPane.showMessageDialog(null, "Successful login");
                    Home h = new Home();
                    h.setVisible(true);
                    //h.pack();
                    //  h.setLocationRelativeTo(null);
                    //h.setExtendedState(Frame.MAXIMIZED_BOTH);
                    // h.jLabel2.setText("Welcome " +user_name + "");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Credentials Try Again");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordFIELD;
    // End of variables declaration//GEN-END:variables
}
